In [2]:
import cv2
import numpy as np
from det_utils import letterbox, scale_coords, nms
from PIL import Image

d:\Applications\Programming\miniconda3\envs\openmmlab\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
image_path = 'fch_ear.jpg' 
img = cv2.imread(image_path)

In [4]:
cv2.namedWindow('Resizable Window', cv2.WINDOW_NORMAL)
cv2.imshow('Resizable Window', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# 确保图像加载成功
if img is not None:
    # 调用 letterbox 函数处理图像
    new_img, ratio, (dw, dh) = letterbox(img)

    # 显示处理后的图像
    cv2.imshow('Letterbox Image', new_img)

    # 等待用户按键，再关闭窗口
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Error: Image not loaded.")

In [14]:
new_img.shape

(640, 640, 3)

In [15]:
a = np.array([1, 2, 3, 4, 5])


In [16]:
a.argmin()

0

In [17]:
a.argmax()

4

In [20]:
b = np.array([[1, 2, 3],
               [4, 5, 6]])

In [22]:
b[0, 1]

2

In [23]:
b.shape

(2, 3)

In [25]:
b[0, 0:2]

array([1, 2])

In [26]:
b[0, :]

array([1, 2, 3])

In [29]:
b[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

-1即从后往前，每次取跨度为1的数

In [30]:
b[0, :: -1]

array([3, 2, 1])

pillow

In [33]:
im = Image.open('fch_ear.jpg')

In [34]:
im.show()

In [35]:
im = np.array(im)

3557行，2836列，有3个颜色分量

In [36]:
im.shape

(3557, 2836, 3)

获取第(100, 100)坐标点的颜色

In [38]:
im[100, 100]

array([26, 27, 29], dtype=uint8)

取出所有像素点的红色分量

In [40]:
im_r = im[:, :, 0]

In [41]:
Image.fromarray(im_r).show()

#### letterbox测试

In [7]:
image = cv2.imread('fch_ear.jpg')

In [8]:
def preprocess_image(image, bgr2rgb=True):
    """图片预处理"""
    img, scale_ratio, pad_size = letterbox(image)
    if bgr2rgb:
        img = img[:, :, ::-1]
    img = img.transpose(2, 0, 1)  # HWC2CHW
    img = np.ascontiguousarray(img, dtype=np.float32)
    return img, scale_ratio, pad_size

In [9]:
img, scale_ratio, pad_size = preprocess_image(image)

In [13]:
img.shape

(3, 640, 640)

In [14]:
cv2.imshow('Letterbox Image', new_img)

# 等待用户按键，再关闭窗口
cv2.waitKey(0)
cv2.destroyAllWindows()